[package]
name = "amnesty-emulator"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
bitflags = { version = "2.10.0", features = ["std"] }
num_enum = "0.7.5"

[dev-dependencies]
pastey = "0.2.0"
