[package]
name = "amnesty-emulator"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
bitflags = { version = "2.9.4", features = ["std"] }
num_enum = "0.7.4"

[dev-dependencies]
paste = "1.0.15"
